/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InsuranceFormRouteImport } from './routes/insuranceForm'
import { Route as ContactFormRouteImport } from './routes/contactForm'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const InsuranceFormRoute = InsuranceFormRouteImport.update({
  id: '/insuranceForm',
  path: '/insuranceForm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactFormRoute = ContactFormRouteImport.update({
  id: '/contactForm',
  path: '/contactForm',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contactForm': typeof ContactFormRoute
  '/insuranceForm': typeof InsuranceFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contactForm': typeof ContactFormRoute
  '/insuranceForm': typeof InsuranceFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contactForm': typeof ContactFormRoute
  '/insuranceForm': typeof InsuranceFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contactForm' | '/insuranceForm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contactForm' | '/insuranceForm'
  id: '__root__' | '/' | '/about' | '/contactForm' | '/insuranceForm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactFormRoute: typeof ContactFormRoute
  InsuranceFormRoute: typeof InsuranceFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/insuranceForm': {
      id: '/insuranceForm'
      path: '/insuranceForm'
      fullPath: '/insuranceForm'
      preLoaderRoute: typeof InsuranceFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactForm': {
      id: '/contactForm'
      path: '/contactForm'
      fullPath: '/contactForm'
      preLoaderRoute: typeof ContactFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactFormRoute: ContactFormRoute,
  InsuranceFormRoute: InsuranceFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
